
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - camunda-cloud.io.camunda
  resources:
  - zeebes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - camunda-cloud.io.camunda
  resources:
  - zeebes/finalizers
  verbs:
  - update
- apiGroups:
  - camunda-cloud.io.camunda
  resources:
  - zeebes/status
  verbs:
  - get
  - patch
  - update
