# permissions for end users to view zeebes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zeebe-viewer-role
rules:
- apiGroups:
  - camunda-cloud.io.camunda
  resources:
  - zeebes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - camunda-cloud.io.camunda
  resources:
  - zeebes/status
  verbs:
  - get
